### ISSUE TITLE
正则表达式

### ISSUE THREAD

**Issue by ruiqiliu** [ruiqiliu/CommonToolsTotorial#11]
### 语法
1. 非打印字符
    + \cx  X指明的控制字符
    + \f \n \r \t \v
    + \s 空白字符  等价于[\f\n\r\t\v]
1. 特殊字符
    + $ 结尾 ^ 首
    + . * + [ ? \ ] |
    + \b 单词边界
    + \w  等价于 `[A-Za-z0-9_]`
1. 预定义模式
    + \d 匹配0-9之间的任一数字，相当于[0-9]。
    + \D 匹配所有0-9以外的字符，相当于[^0-9]。
    + \w 匹配任意的字母、数字和下划线，相当于[A-Za-z0-9_]。
    + \W 除所有字母、数字和下划线以外的字符，相当于[^A-Za-z0-9_]。
    + \s 匹配空格（包括换行符、制表符、空格符等），相等于[ \t\r\n\v\f]。
    + \S 匹配非空格的字符，相当于[^ \t\r\n\v\f]。
    + \b 匹配词的边界。
    + \B 匹配非词边界，即在词的内部。
1. 贪婪模式与非贪婪模式
    + `+ and *` 默认是贪婪模式，匹配到下一次字符不能匹配位置
    + `+? and *?`添加`?`以后，采用非贪婪模式
1. 组匹配
    + 可以通过捕获组获取对应的匹配结果
    + `(?:x)` Non-capturing group， 不单独输出该捕获组结果
    + 先行断言 `x(?=y)` Positive look-ahead
    + 先行否定断言 `x(?!y)` Negative look-ahead

## 实例

- 匹配中文字符： `[\u4e00-\u9fa5] `
- 匹配空行： `^\s*$`
- 匹配HTML标签： `/<(.*)>.*<\/\1>|<(.*) \/>/ `
- 匹配Email标签： `\S+@\S+\.\S+`  非精确匹配
- 匹配URL： `[a-zA-Z]+://(\w+(-\w+)*(.\w+(-\w+)*)*)(:\d+)?(\S*)?`

### JavaScript

1. 新建正则式 
1. exec or test
1. string相关实例方法：match\search\replace\split
``` JavaScript
var regex = /xyz/igm
var reg2 = new RegExp('xyz','igm')
// 一些只读属性：
// RegExp.prototype.ignoreCase 
// RegExp.prototype.multiline
// RegExp.prototype.global
// RegExp.prototype.source 返回正则式的字符串形式（不包括反斜杠）
```  
##  参考资料

- http://www.runoob.com/regexp/regexp-syntax.html
- http://javascript.ruanyifeng.com/stdlib/regexp.html
- [在线校验工具]()

**Comment by ruiqiliu** [comment]
## 函数式编程

- 高阶函数（表达力强）： Functions that operate on other functions
- 没有副作用：不修改外部变量的值，提高并行能力，执行顺序随意
## Scala Quick Guide

Functionality： 

- All types are objects
- Type inference
- Nested Functions
- Functions are objects
- Domain specific language (DSL) support
- Traits
- Closures
- Concurrency support inspired by Erlang

### Basic Syntax

- Object: an instance of a class, consist of states and behaviors
- Class: a template to describe the behaviros
- Methods: a behavior
- Fields: instance variables of each object
- Closure: A closure is a function, whose return value depends on the value of one or more variables declared outside this function
- Traits: encapsulate method and field definitions for re-using

### Scala Identifiers

- Alphanumberic Identifiers: same to Java
- Operator Indetifiers: ++ ::: <?> :>
  + :> 类型定界
- Mixed Identifies: alp_ident followed by _ and oper_ident
- Literal Indentifies: any string enclosed by back ticks(`test`)

### Scala key words

``` Scala
abstract	case	catch	class
def	do	else	extends
false	final	finally	for
forSome	if	implicit	import
lazy	match	new	Null
object	override	package	private
protected	return	sealed	super
this	throw	trait	Try
true	type	val	Var
while	with	yield	 
-	:	=	=>
<-  循环迭代
<:	
<% 
：隐式转换	
>: 下边界
#	@
```


### Scala Data Type

Same As Java
1. Byte 8 bit signed value. Range from -128 to 127
2. Short 16 bit signed value. Range -32768 to 32767
3. Int 32 bit signed value. Range -2147483648 to 2147483647
4. Long  64 bit signed value. -9223372036854775808 to 9223372036854775807
5. Float  32 bit IEEE 754 single-precision float
6. 	Double 64 bit IEEE 754 double-precision float
7. Char 16 bit unsigned Unicode character. Range from U+0000 to U+FFFF
8. String A sequence of Chars
9.	Boolean Either the literal true or the literal false
10.	Unit Corresponds to no value
11. Null null or empty reference
12. Nothing The subtype of every other type; includes no values
13. 	Any The supertype of any type; any object is of type Any
14.	AnyRef  The supertype of any reference type

```SCALA
"""the present string
spans three
lines."""

```

#### option

- https://alvinalexander.com/scala/scala-option-some-none-syntax-examples


### RDD 基础操作

- 创建RDD： 
    + sc.makeRDD(List(123,2,4,5,6))
    + sc.makeRDD(Array(1,2,34,5,6))
    + sc.paralize(List(1,23,4,5,6),1)
    + val rdd:RDD[String] = sc.textFile("file:///D:/spark.txt,1)
- 转化操作：
    + map：对每个元素操作
    + flatMap：map + join or flattern
    + filter：过滤掉不符合条件的元素
    + distinct：无参， 对元素去重
    + union： 参数是RDD，合并两个RDD
    + intersection： 参数是RDD，取交集
    + subtract： 参数RDD， 减法
    + cartesian： 求笛卡尔积
    + groupByKey：When called on a dataset of (K, V) pairs, returns a dataset of (K, Iterable<V>) pairs. 
    + reduceByKey
    + pipe

- 行动操作：    
    + collect： 返回所有元素
    + first
    + take n
    + takeSample
    + count： 返回元素个数
    + countByValue： 各元素在RDD中出现的次数
    + reduce： 并行整合RDD
    + fold(0)(func):  带有初始值的reduce
    + aggregate
    + foreach ： 对RDD的每个元素使用特殊函数

### `_`的用法

1. var name:String=_   //initialize to null
1. import math._  // import math.*
1. xx.map(_*2) // represent a value ; same as this
1. Match: case _ => "your default result" // same as  case default: xx
1. tuple._1 // get the fisrt value same as: tuple.productElement(0)


## 实战 

- scalac xxPackage/xxClass.scala
- scala xxPackage.xxClass
- CLASSPATH=%JAVA_HOME%\lib;%SCALA_HOME%\lib;.
- `:load xxx.scala`

- IDEA：run scala console and type in expression and ctr+enter
### Option and Some


- 创建 使用[Link](https://windor.gitbooks.io/beginners-guide-to-scala/content/chp5-the-option-type.html)

- case classes: used to Modeling immutable data and compared by structure,not by reference

### apply & unapply
```Scala
import scala.util.Random

object CustomerID {

  def apply(name: String) = s"$name--${Random.nextLong}"

  def unapply(customerID: String): Option[String] = {
    val stringArray: Array[String] = customerID.split("--")
    if (stringArray.tail.nonEmpty) Some(stringArray.head) else None
  }
}

val customer1ID = CustomerID("Sukyoung")  // Sukyoung--23098234908
customer1ID match {
  case CustomerID(name) => println(name)  // prints Sukyoung
  case _ => println("Could not extract a CustomerID")
}
```

### String

```Scala
 val str = s"first($child)${if (ignoreNulls) " ignore nulls"}"
```
- https://docs.scala-lang.org/tour/extractor-objects.html

### setMaster 

- local 本地单线程
- local[K] 本地多线程（指定K个内核）
- local[*] 本地多线程（指定所有可用内核）
- spark://HOST:PORT 连接到指定的 Spark standalone cluster master，需要指定端口。
- mesos://HOST:PORT 连接到指定的 Mesos 集群，需要指定端口。
- yarn-client客户端模式 连接到 YARN 集群。需要配置 HADOOP_CONF_DIR。
- yarn-cluster集群模式 连接到 YARN 集群 。需要配置 HADOOP_CONF_DIR

## 参考资料

- https://www.tutorialspoint.com/scala/scala_quick_guide.htm
- https://spark.apache.org/docs/2.1.1/programming-guide.html 官方Guide
- file:///D:/Develop/scala216/doc/tools/scala.html

**Comment by ruiqiliu** [comment]
## YAML入门

YAML 是专门用来写配置文件的语言，非常简洁和强大，远比 JSON 格式方便。

 - 大小写敏感
 - 使用缩进来区分层级，不使用Tab键，一律使用空格，空格的数目不重要，只要向左对齐就行
 - ‘#’ 表示 单行注释
 - 支持三种数据结构：
   + 对象： 键值对 （mapping\hashes\dictionary)
        ```yaml
        animal: pets 
        ```
   + 数组： 按次序排列的值（sequence\list）
        ```yaml
        - Cat
        - 
          - Dog # 嵌套数组
          - Dog2
          - Dog3
        - Goldfish
        ```
   + 纯量（scalars）：单个的不可再分的值
        ```yaml
        isSet : true #布尔值
        number:  123 #整数
        floatNumber: 12.34#浮点数
        parent:null #Null
        iso8601: 2001-12-14t21:59:43.10-05:00 #时间
        date: 1976-07-31# 日期
        e：!!str 123 #YAML 允许使用两个感叹号，强制转换数据类型。
        ```
    + 字符串： 
        1. 默认不用引号
        2. 有空格或者特殊字符需要用引号
        3. 单双引号都可以，双引号不会对特殊字符转义（保存的值等于字面值）
        4. 字符串可以写成多行，从第二行开始，必须有一个单空格缩进。换行符会被转为空格
        5. JSON串：  `{ this: 'Foo\nBar\n', that: 'Foo Bar\n' }`
            ``` yaml
            this: | # |表示保留换行符
                Foo
                Bar
            that: > # >表示折叠换行
                Foo
                Bar
            ```

   + 复合结构
        ```yaml
        languages:
            - Ruby
            - Perl
            - Python 
        websites:
            YAML: yaml.org 
            Ruby: ruby-lang.org 
            Python: python.org 
            Perl: use.perl.org 
        ```

    + 引用:&用来建立锚点（defaults），<<表示合并到当前数据，*用来引用锚点。
        ```yaml
        defaults: &defaults
            adapter:  postgres
            host:     localhost

        development:
            database: myapp_development
            <<: *defaults

        test:
            database: myapp_test
            <<: *defaults
        ```
 
        等价于如下yaml
        ```yaml
        defaults:
            adapter:  postgres
            host:     localhost

        development:
            database: myapp_development
            adapter:  postgres
            host:     localhost

        test:
            database: myapp_test
            adapter:  postgres
            host:     localhost
        ```

## 参考资料
- [阮一峰的博客](http://www.ruanyifeng.com/blog/2016/07/yaml.html)
- [在线YAML编辑器](http://nodeca.github.io/js-yaml/)
- [YAML Ain't ML](http://www.yaml.org/spec/1.2/spec.html)
